### PR TITLE
chore: add autorelease scripts

### PR DESCRIPTION
**Pull request by skuruppu**

### CODE REVIEW

**Comment by skuruppu** [comment]
I got it to work. It wasn't the .NET 3.1 thing in the end. It was because of the line `export DeterministicSourcePaths=true` in `buildrelease.sh`. I'll have to ask the C# team on how to do local builds given that this doesn't work.

**Comment by skuruppu** [comment]
@olavloite I've setup the Kokoro release job on the backend so we can submit this to see if we can get a release to work.

As for the test failure, I'm not sure why this is happening:
```
[xUnit.net 00:00:00.88]       System.AggregateException : One or more errors occurred. (Please set the TEST_PROJECT environment variable to your test project ID before running tests) (The following constructor parameters did not have matching fixture data: ShadowPropertiesTestFixture fixture)
[xUnit.net 00:00:00.88]       ---- System.InvalidOperationException : Please set the TEST_PROJECT environment variable to your test project ID before running tests
[xUnit.net 00:00:00.88]       ---- The following constructor parameters did not have matching fixture data: ShadowPropertiesTestFixture fixture
[xUnit.net 00:00:00.89]       Stack Trace:
```

It may just be one of those things where the env variable is not available if you're running from a fork rather than a branch on the main repo. I see that the tests pass in some of your PRs.

**Comment by olavloite** [comment]
> It may just be one of those things where the env variable is not available if you're running from a fork rather than a branch on the main repo. I see that the tests pass in some of your PRs.

Yes, that is most probably the reason. I think we should split the integration tests for production from the current single GitHub Actions file, and then also skip those tests when a PR is coming from a fork [like we did for ActiveRecord](https://github.com/googleapis/ruby-spanner-activerecord/pull/121).

**Comment by skuruppu** [comment]
BTW I also renamed the version from 1.0.0-beta to 0.1.0 to match the release tag. Let me know if you have any concerns about that.

**Review by olavloite — APPROVED** [review]

**Pull request merged**
