### PR TITLE
feat: Targetting .NET 8

### LINKED ISSUE #386: When will you target .net 8?
We use the Google.Cloud.EntityFrameworkCore.Spanner library in our .net 6 application. We are upgrading to use .net 8 given that .net 6 will no longer be supported by MS after Nov 2024.  However, we're encountering a runtime error from our DbContext constructor with the spanner provider that is not present when we run with .net 6:

`Method 'FindMapping' in type 'Google.Cloud.EntityFrameworkCore.Spanner.Storage.Internal.SpannerTypeMappingSource' from assembly 'Google.Cloud.EntityFrameworkCore.Spanner, Version=2.1.3.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.`

We are also wary about having a dependency on a library that targets a version of .net that will be out of support soon.

Do you expect to update the EF provider for spanner to target .net 8 soon?

### PR DESCRIPTION
**Pull request by shawncrabtree**
This updates the package to target .NET Core 8

Fixes #386

- [Y] Tests pass
- [Y] Appropriate changes to README are included in PR

### CODE REVIEW

**Review by ANIZA15 — APPROVED** [review]

**Comment by ANIZA15** [comment]
Please merge.

**Comment by shawncrabtree** [comment]
> Please merge.

Thank you for approving! Unfortunately merging is still blocked. It looks like I need approval from someone with read access in this repo

**Comment by ANIZA15** [comment]
> Thank you for approving! Unfortunately merging is still blocked. It looks like I need approval from someone with read access in this repo

I see! Now we just have to wait for the approval of the person who has the authority! I personally hope it gets merged as soon as possible.

**Comment by olavloite** [comment]
@shawncrabtree @ANIZA15 Thanks for looking into this. I'll take a look this week to see if we can merge this as is, or whether we need some additional testing.
We also need to determine whether this requires a major version bump of this library or not, as we are doing a major version bump of one of the dependencies that it relies on.

**Comment by olavloite** [comment]
@shawncrabtree @ANIZA15 I think that for the time being, it is better to target both .NET 6 and .NET 8. That prevents introducing a breaking change at this moment. Later, when we also update to Entity Framework 8, then we require .NET 8 and it will be a breaking change.

See #403

**Comment by ANIZA15** [comment]
@olavloite 
It is true that if both .net6 and .net8 are available, it would be better for users to have more options!

**Comment by shawncrabtree** [comment]
That sounds good to me. I'll drop this PR in favor of the one from @olavloite
https://github.com/googleapis/dotnet-spanner-entity-framework/pull/403/files

**Pull request closed without merging**
